
## Code Book for "Means.txt"" (output of the run_analysis script)

Original Files
    *Full data set: https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip
    
    *Description of study can be found here: 
 	http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

###Columns in the Means.txt output file

The output file (Means.txt) contains means for each subject for each of the activities for each of the means and standard deviation variables of the full dataset (66 variables, with Subject and Activity as IDs). Means and standard deviations were only included into this set if the mean or std was at the end of the variable name, not with the first part of the variable name. All variables are listed below: 
    *"Subject" 
    *"Activity" 
    *"tBodyAcc-mean()-X" 
    *"tBodyAcc-mean()-Y" 
    *"tBodyAcc-mean()-Z" 
    *"tBodyAcc-std()-X" 
    *"tBodyAcc-std()-Y" 
    *"tBodyAcc-std()-Z" 
    *"tGravityAcc-mean()-X" 
    *"tGravityAcc-mean()-Y" 
    *"tGravityAcc-mean()-Z" 
    *"tGravityAcc-std()-X" 
    *"tGravityAcc-std()-Y" 
    *"tGravityAcc-std()-Z" 
    *"tBodyAccJerk-mean()-X" 
    *"tBodyAccJerk-mean()-Y" 
    *"tBodyAccJerk-mean()-Z" 
    *"tBodyAccJerk-std()-X" 
    *"tBodyAccJerk-std()-Y" 
    *"tBodyAccJerk-std()-Z" 
    *"tBodyGyro-mean()-X" 
    *"tBodyGyro-mean()-Y" 
    *"tBodyGyro-mean()-Z" 
    *"tBodyGyro-std()-X" 
    *"tBodyGyro-std()-Y" 
    *"tBodyGyro-std()-Z" 
    *"tBodyGyroJerk-mean()-X" 
    *"tBodyGyroJerk-mean()-Y" 
    *"tBodyGyroJerk-mean()-Z" 
    *"tBodyGyroJerk-std()-X" 
    *"tBodyGyroJerk-std()-Y" 
    *"tBodyGyroJerk-std()-Z" 
    *"tBodyAccMag-mean()" 
    *"tBodyAccMag-std()" 
    *"tGravityAccMag-mean()" 
    *"tGravityAccMag-std()" 
    *"tBodyAccJerkMag-mean()" 
    *"tBodyAccJerkMag-std()" 
    *"tBodyGyroMag-mean()" 
    *"tBodyGyroMag-std()" 
    *"tBodyGyroJerkMag-mean()" 
    *"tBodyGyroJerkMag-std()" 
    *"fBodyAcc-mean()-X" 
    *"fBodyAcc-mean()-Y" 
    *"fBodyAcc-mean()-Z" 
    *"fBodyAcc-std()-X" 
    *"fBodyAcc-std()-Y" 
    *"fBodyAcc-std()-Z" 
    *"fBodyAccJerk-mean()-X" 
    *"fBodyAccJerk-mean()-Y" 
    *"fBodyAccJerk-mean()-Z" 
    *"fBodyAccJerk-std()-X" 
    *"fBodyAccJerk-std()-Y" 
    *"fBodyAccJerk-std()-Z" 
    *"fBodyGyro-mean()-X" 
    *"fBodyGyro-mean()-Y" 
    *"fBodyGyro-mean()-Z" 
    *"fBodyGyro-std()-X" 
    *"fBodyGyro-std()-Y" 
    *"fBodyGyro-std()-Z" 
    *"fBodyAccMag-mean()" 
    *"fBodyAccMag-std()" 
    *"fBodyBodyAccJerkMag-mean()" 
    *"fBodyBodyAccJerkMag-std()" 
    *"fBodyBodyGyroMag-mean()" 
    *"fBodyBodyGyroMag-std()" 
    *"fBodyBodyGyroJerkMag-mean()" 
    *"fBodyBodyGyroJerkMag-std()"
	
